### ISSUE TITLE
Dynamic scene nodes lost when combining osg with imgui. 

### ISSUE THREAD

**Issue by blackball** [Tordan/imgui-osg#1]
Hi, 

Thanks for your great example codes on combining osg with imgui. 

I am trying to use it in one of my small project. I need to draw some boxes with osg at the run time, when there's no imgui, everything is fine. But when I added an simplest eventhandler of imgui, like you demostrated in the example codes, the first box will be drawn, but no the later ones. 

basically the osg rendering loop is like: 
```C++
viewer->addEventHandler(new ImGuiWindow);
while (!done()) {
  frame(); 
  AddBoxToTheSceneRoot(); 
}
```

I stepped into the codes, and found that if I replace the RenderDrawData function from: https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_opengl2.cpp#L118

with a simpler one: https://gist.github.com/fulezi/d2442ca7626bf270226014501357042c#file-imguihandler-cpp-L19

The boxes will be shown, but the color is not correct. 

So I guess, there's something wrong by just integrating imgui with osg directly here. Seems like imgui's RenderRawData function is overwriting some states of OSG here. 

Since I am not an OpenGL expert, I would like to have your advice, to see how we could fix these issues robustly. 

Thanks very much!

**Comment by blackball** [comment]
I found that the issue is caused by following codes: 
```C++
    glDisableClientState(GL_COLOR_ARRAY);
    glDisableClientState(GL_TEXTURE_COORD_ARRAY);
    glDisableClientState(GL_VERTEX_ARRAY);
```
FYI

**Comment by Tordan** [comment]
Hi,

What version of OSG and ImGui do you use?
Your first link goes to OpenGL**2** implementation, which is strange because this demo is hardcoded to use OpenGL**3** implementation provided by ImGui.

**Comment by blackball** [comment]
I am using the latest OSG compiled from the source. And you are right, I just realized that I have changed it to OpenGL2 at some point..
