### ISSUE TITLE
io.RenderDrawListsFn was removed with imgui 1.80

### ISSUE THREAD

**Issue by ltoenning** [Tordan/imgui-osg#2]
Since imgui 1.80 ``io.RenderDrawListsFn`` doesn't exist any more. [See the changelog here.](https://github.com/ocornut/imgui/blob/0cdc4a956530cbe64a4e319446f8d9d2d7d149ee/imgui.cpp#L427`)

It is used here: https://github.com/Tordan/imgui-osg/blob/31f4ea6a15ba88613c2bc307a7451bb731c08964/src/OsgImGuiHandler.cpp#L123

I made a quick and dirty fix by changing ``OsgImGuiHandler::render()``:

```cpp
void OsgImGuiHandler::render(osg::RenderInfo&)
{
    drawUi();
    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
}
```

But I'm not sure if this is the recommended way by calling this explicitly on every frame.

**Comment by Tordan** [comment]
Hi,

Thanks for pointing that out! 

> But I'm not sure if this is the recommended way by calling this explicitly on every frame.

It looks totally fine to me, at least that's what they do in official examples.

 I've updated the code and it should work out of the box with the newest version of ImGui.

**Comment by ltoenning** [comment]
Thanks for the quick fix!

Works as expected!
